### ISSUE TITLE
Design Docs - Database Schema

### ISSUE THREAD

**Issue by huangs2022672** [ashes4trees/napflix#3]
Hi Stephanie, great job on the schema!!

# Database Schema
​
- [x] Contains correct datatypes
- [x]  Contains appropriate constraints/details
    - [x]  primary key
    - [x]  not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
    - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
​
### Comments

* for users, I'm not sure you'll need both a name and a username
* for movies, are you keeping movie rating static? would users be able to update this? might make a good bonus feature w/ a ratings table

**Comment by huangs2022672** [comment]
- you probably don't need `index on [:genre_id, :id], unique: true` b/c :id is always going to be unique
- any particular reason for changing genre from a string to a foreign_key and adding a genres table?

**Comment by ashes4trees** [comment]
I must have lost the thread somewhere. I wanted to create a joins table between genres and movies so a movie can have multiple genres. I added that now, called 'categories'.
