### ISSUE TITLE
Design Docs - Backend Routes

### ISSUE THREAD

**Issue by huangs2022672** [ashes4trees/napflix#4]
Great job Stephanie!

# Backend Routes
​
- [x]  Contains the following sections: HTML, API Endpoints(Backend)
- [x]  Each route has a description
- [x]  API Endpoint routes contains wildcard variables written in `snake_case`
- [x]  Routes does not contain superfluous routes
- [x]  Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    -  i.e. probably don't need a `GET likes` api endpoint because that info comes through the post show
​
### Comments

* with users, remember not to allow the demo user account to be deleted =]

* for nested routes, such as users, it should be `:user_id` instead of `:id`

* you might want a mylist index to show the movies under mylist of a profile

**Comment by huangs2022672** [comment]
Hi Stephanie,

mylist `GET /api/lists/:list_id` returns one item in the mylist table, it is an association between a profile and a movie, not an index of movies in mylist

**Comment by ashes4trees** [comment]
I originally had it that the profile GET request would also return the list data... I think that's preferable anyway?

**Comment by huangs2022672** [comment]
yes, that works
