### ISSUE TITLE
Design Docs - Sample State

### ISSUE THREAD

**Issue by huangs2022672** [ashes4trees/napflix#5]
Great job Stephanie! very very minor notes at the bottom

# Sample State
​
- [x] State shape is flat!
- [x]  State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language `(```javascript...```)`. This will display the state as a code block instead of a giant line of text
    - [x]  Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka `comments` inside of `posts`
        - Some info from other tables is ok, for instance:
            - the author username and imageurl for a post. basically any info that the user can't change
            - like count and a boolean on whether the user likes the post instead of a likes slice
​
### Comments

- not sure how necessary it is to keep an array of profileIds in the user pojo, what would be a use case?
- adding and deleting a movie from your list will probably be accomplished using the same button, using conditional logic of whether the movie is already in your list, so you probably won't need error messages for your lists.

**Comment by ashes4trees** [comment]
Thanks Sammy! I removed both of the items referenced in your comments.
